### ISSUE TITLE
Yay build error - no rule to make libboost dependencies

### ISSUE THREAD

**Issue by michael-obroin** [ros-melodic-arch/ros-melodic-gazebo-ros#6]
I'm using yay to install the ros-melodic-desktop-full metapackage, but I get an error when finishing the build step for ros-melodic-gazebo-ros. The current version of the boost library is 1.72.0, but gazebo keeps referring to version 1.71.0 of various components from it.

>Scanning dependencies of target gazebo_ros_api_plugin
Scanning dependencies of target gazebo_ros_paths_plugin
make[2]: Leaving directory '/home/ob/.cache/yay/ros-melodic-gazebo-ros/src/build'
make[2]: Entering directory '/home/ob/.cache/yay/ros-melodic-gazebo-ros/src/build'
make[2]: *** No rule to make target '/usr/lib64/libboost_program_options.so.1.71.0', needed by 'devel/lib/libgazebo_ros_paths_plugin.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object CMakeFiles/gazebo_ros_paths_plugin.dir/src/gazebo_ros_paths_plugin.cpp.o
make[2]: Leaving directory '/home/ob/.cache/yay/ros-melodic-gazebo-ros/src/build'
make[2]: Entering directory '/home/ob/.cache/yay/ros-melodic-gazebo-ros/src/build'
make[2]: *** No rule to make target '/usr/lib64/libboost_program_options.so.1.71.0', needed by 'devel/lib/libgazebo_ros_api_plugin.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 60%] Building CXX object CMakeFiles/gazebo_ros_api_plugin.dir/src/gazebo_ros_api_plugin.cpp.o
make[2]: Leaving directory '/home/ob/.cache/yay/ros-melodic-gazebo-ros/src/build'
make[1]: *** [CMakeFiles/Makefile2:1202: CMakeFiles/gazebo_ros_paths_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/ob/.cache/yay/ros-melodic-gazebo-ros/src/build'
make[1]: *** [CMakeFiles/Makefile2:650: CMakeFiles/gazebo_ros_api_plugin.dir/all] Error 2
make[1]: Leaving directory '/home/ob/.cache/yay/ros-melodic-gazebo-ros/src/build'
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ros-melodic-gazebo-ros

**Comment by bionade24** [comment]
You have to rebuild the dependencies that were linked against previous boost or downgrade boost. This is not an issue.

**Comment by maujim** [comment]
@bionade24 I'm encountering the same error. How would I go about rebuilding the deps that were linked against previous boost?

**Comment by acxz** [comment]
@michael-obroin @maujim First you need to uninstall all ros-melodic-* packages. This can be done as follows:
`yay -Rns $(yay -Qsq ros-melodic)`
Then you need to remove existing build directories, like so (if using yay)
`rm -rf ~/.cache/yay/ros-melodic-*`
Now you can reinstall/rebuild your ros packages, like so
`yay -Syu ros-melodic-gazebo-ros`

Please let us know if this does not work.

**Comment by michael-obroin** [comment]
Out of curiosity, would this have the same effect as yay --rebuildtree -Syu ros-melodic-gazebo-ros? I will try your suggestion now.

**Comment by maujim** [comment]
I've had issues using the `--rebuildtree` flag: https://github.com/Jguer/yay/issues/1141

**Comment by bionade24** [comment]
Probably because something was built in the wrong order.

**Comment by maujim** [comment]
@acxz still getting the same error with the steps you suggested. I also tried `yay --rebuildtree -Syu ros-melodic-gazebo-ros` first and that rebuilt `gazebo` but still led to the same error.

**Comment by acxz** [comment]
@maujim did you confirm that all ros related packages were uninstalled before starting the reinstall?
Oh wait since this is a package that depends on gazebo, you also need to make sure gazebo is rebuilt and potentially *its* dependencies. Let me do the reinstall on my end and see if I can reproduce the error or not.

**Comment by bionade24** [comment]
In some hours you could use my binary repo too. I had issues in my pacman cache again, so it didn't build.

**Comment by maujim** [comment]
@acxz I did confirm. I removed gazebo and all dependencies and am currently rebuilding. Will let you know the result

**Comment by michael-obroin** [comment]
> Now you can reinstall/rebuild your ros packages, like so
> `yay -Syu ros-melodic-gazebo-ros`

If I originally installed the ros-melodic-desktop-full package, this step should be `yay -Syu ros-melodic-desktop-full` for me, right?

**Comment by acxz** [comment]
@michael-obroin Sure yeah, but let's try to first install this package, since this was the one that gave you the error. One step at a time, :)

**Comment by maujim** [comment]
I made sure to explicitly remove `boost-libs` and its dependencies but I'm still getting the same error :(

**Comment by bionade24** [comment]
> Still getting the same error :(

Please simply wait until my binaries are built. When at least ros-melodic-desktop is completed your boost problems should be overriden. You probably did not purged all ros packages from  your system.

**Comment by acxz** [comment]
Just piping in that I cannot reproduce this error after a clean rebuild.

**Comment by bionade24** [comment]
Please use my repo now instead of investing hours in rebuilding packages that don't work afterwards. Guide is in the Archlinux ROS discourse thread or the first comment here: https://aur.archlinux.org/packages/ros-melodic-desktop-full/

**Comment by jwhendy** [comment]
@bionade24 would you propose this for *all* packages moving forward? Namely, this repo is for ironing out bugs, but ROS on arch should be binary only (where possible) via your repo? If so, might I suggest adding this info to [the wiki](https://wiki.archlinux.org/index.php/ROS) vs. just AUR comments? "ROS on arch" will point there for most new users vs. AUR pages (even though the pinned comment is certainly a nice touch).

**Comment by maujim** [comment]
@bionade24 thanks for your help. Side question: if I have your binary repo set up, do I really need to have `arch4edu` also set up? I only ask because its the recommended binary repo to use [as per the ROS wiki](http://wiki.ros.org/melodic/Installation/ArchLinux)

**Comment by bionade24** [comment]
> @bionade24 would you propose this for _all_ packages moving forward? Namely, this repo is for ironing out bugs, but ROS on arch should be binary only (where possible) via your repo? If so, might I suggest adding this info to [the wiki](https://wiki.archlinux.org/index.php/ROS) vs. just AUR comments? "ROS on arch" will point there for most new users vs. AUR pages (even though the pinned comment is certainly a nice touch).

I'll add that. But at the moment I'll look foward to get problematic core part into community repo.

**Comment by bionade24** [comment]
> @bionade24 thanks for your help. Side question: if I have your binary repo set up, do I really need to have `arch4edu` also set up? I only ask because its the recommended binary repo to use [as per the ROS wiki](http://wiki.ros.org/melodic/Installation/ArchLinux)

If you use mine, you don't need arch4edu. At the moment a4e has not mot much ROS packages as I'll try to get some parts into community repo. If this works the plan is to get the rest like pcl or gazebo related packages into arch4edu.
